package com.kuncms.pay.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.stereotype.Component;
@Component
public class WechatpayTradeinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.nonce_str
     *
     * @mbggenerated
     */
    private String nonceStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.code_url
     *
     * @mbggenerated
     */
    private String codeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.total_fee
     *
     * @mbggenerated
     */
    private int totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.body
     *
     * @mbggenerated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_tradeinfo.status
     *
     * @mbggenerated
     */
    private String status;
    private String flag;
    
    private String time_end;
    public String getTime_end() {
		return time_end;
	}

	public void setTime_end(String time_end) {
		this.time_end = time_end;
	}

    public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	
    
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.id
     *
     * @return the value of wechatpay_tradeinfo.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.id
     *
     * @param id the value for wechatpay_tradeinfo.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.out_trade_no
     *
     * @return the value of wechatpay_tradeinfo.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.out_trade_no
     *
     * @param outTradeNo the value for wechatpay_tradeinfo.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.nonce_str
     *
     * @return the value of wechatpay_tradeinfo.nonce_str
     *
     * @mbggenerated
     */
    public String getNonceStr() {
        return nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.nonce_str
     *
     * @param nonceStr the value for wechatpay_tradeinfo.nonce_str
     *
     * @mbggenerated
     */
    public void setNonceStr(String nonceStr) {
        this.nonceStr = nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.code_url
     *
     * @return the value of wechatpay_tradeinfo.code_url
     *
     * @mbggenerated
     */
    public String getCodeUrl() {
        return codeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.code_url
     *
     * @param codeUrl the value for wechatpay_tradeinfo.code_url
     *
     * @mbggenerated
     */
    public void setCodeUrl(String codeUrl) {
        this.codeUrl = codeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.total_fee
     *
     * @return the value of wechatpay_tradeinfo.total_fee
     *
     * @mbggenerated
     */
    public int getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.total_fee
     *
     * @param total_fee the value for wechatpay_tradeinfo.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(int total_fee) {
        this.totalFee = total_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.create_time
     *
     * @return the value of wechatpay_tradeinfo.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.create_time
     *
     * @param createTime the value for wechatpay_tradeinfo.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.create_by
     *
     * @return the value of wechatpay_tradeinfo.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.create_by
     *
     * @param createBy the value for wechatpay_tradeinfo.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.update_time
     *
     * @return the value of wechatpay_tradeinfo.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.update_time
     *
     * @param updateTime the value for wechatpay_tradeinfo.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.update_by
     *
     * @return the value of wechatpay_tradeinfo.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.update_by
     *
     * @param updateBy the value for wechatpay_tradeinfo.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.body
     *
     * @return the value of wechatpay_tradeinfo.body
     *
     * @mbggenerated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.body
     *
     * @param body the value for wechatpay_tradeinfo.body
     *
     * @mbggenerated
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_tradeinfo.status
     *
     * @return the value of wechatpay_tradeinfo.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_tradeinfo.status
     *
     * @param status the value for wechatpay_tradeinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}